### PR TITLE
Return Status from CoreWorker function and remove RAY_CHECK

### LINKED ISSUE #84: Avoid using `RAY_CHECK*`
> We shouldn't be using `RAY_CHECK*` because when it fails, it exits the process.  better to check + throw.  but we can handle that in a cleanup later.

_Originally posted by @kleinschmidt in https://github.com/beacon-biosignals/ray_core_worker_julia_jll.jl/pull/83#discussion_r1317280854_

### PR DESCRIPTION
**Pull request by glennmoy**
Closes #84

### CODE REVIEW

File: build/wrapper.cc [hunk 1]
```diff
@@ -110,13 +110,18 @@ void initialize_worker(
...
           // https://github.com/beacon-biosignals/Ray.jl/issues/54
-          (*returns)[0].second = return_vec[0];
-          return Status::OK();
+          if (return_vec.size() == 1) {
+            (*returns)[0].second = return_vec[0];
+            return Status::OK();
+          } 
+          else {
+            auto msg = "Task returned too many values: " + std::to_string(return_vec.size());
+            return Status::Invalid(msg);
```
Comment (glennmoy) [inline build/wrapper.cc:121]: unsure what type of `Status` we want to return here? I went with `Invalid` as it seemed the most generic

Comment (omus) [reply build/wrapper.cc:121]: `NotImplemented` seems appropriate

File: build/wrapper.cc [hunk 2]
```diff
@@ -187,7 +192,10 @@ ObjectID put(const std::shared_ptr<RayObject> object,
 
     // Store our data in the object store
     ObjectID object_id;
-    RAY_CHECK_OK(worker.Put(*object, contained_object_ids, &object_id));
+    auto status = worker.Put(*object, contained_object_ids, &object_id);
+    if (!status.ok()) {
+        throw std::runtime_error(status.ToString());
+    }
     return object_id;
```
Comment (omus) [inline build/wrapper.cc:199]: So the actual [`CoreWorker::Put`](https://github.com/ray-project/ray/blob/a03efd9931128d387649dd48b0e4864b43d3bfb4/src/ray/core_worker/core_worker.h#L558-L560) returns just `Status` and passes back the `object_id` by reference. I'd try that approach here.

File: build/wrapper.cc [hunk 3]
```diff
@@ -200,10 +208,15 @@ std::shared_ptr<RayObject> get(const ObjectID object_id, int64_t timeout_ms) {
...
+    }
+
+    if (objects.size() != 1) {
+        auto msg = "Size of RayObjects is " + std::to_string(objects.size());
+        auto st = Status::Invalid(msg);
+        throw std::runtime_error(st.ToString());
     }
 
-    RAY_CHECK(objects.size() == 1);
     return objects[0];
```
Comment (omus) [inline build/wrapper.cc:220]: Similarly to `CoreWorker::Put` we should have [`CoreWorker::Get`](https://github.com/ray-project/ray/blob/a03efd9931128d387649dd48b0e4864b43d3bfb4/src/ray/core_worker/core_worker.h#L665-L667) return a `Status` and pass back the object by reference.

File: build/wrapper.cc [hunk 4]
```diff
@@ -200,10 +208,15 @@ std::shared_ptr<RayObject> get(const ObjectID object_id, int64_t timeout_ms) {
...
     if (!status.ok()) {
-        return nullptr;
+        throw std::runtime_error(status.ToString());
+    }
+
+    if (objects.size() != 1) {
+        auto msg = "Size of RayObjects is " + std::to_string(objects.size());
+        auto st = Status::Invalid(msg);
+        throw std::runtime_error(st.ToString());
     }
```
Comment (omus) [inline build/wrapper.cc:218]: This is an internal error as the caller can only specify one object to get. As there is no "InternalError" I think "UnknownError" probably fits best:
```suggestion
    if (objects.size() != 1) {
        auto msg = "Requested a single object but instead found " + std::to_string(objects.size()) + " objects.";
        auto st = Status::UnknownError(msg);
        throw std::runtime_error(st.ToString());
    }
```

File: build/wrapper.cc (hunk 2 above)
Comment (omus) [reply build/wrapper.cc:199]: It's definitely a little bit of scope creep but it should clean things up nicely

File: build/wrapper.cc [hunk 5]
```diff
@@ -110,13 +110,18 @@ void initialize_worker(
...
-          (*returns)[0].second = return_vec[0];
-          return Status::OK();
+          if (return_vec.size() == 1) {
+            (*returns)[0].second = return_vec[0];
+            return Status::OK();
+          } 
+          else {
+            auto msg = "Task returned " + std::to_string(return_vec.size()) + " values. Expected 1.";
+            return Status::NotImplemented(msg);
+          };
```
Comment (glennmoy) [inline build/wrapper.cc:122]: I don't think there's any need for this restriction anymore... I'll make a quick attempt to obviate it

Comment (glennmoy) [reply build/wrapper.cc:122]: moving this into https://github.com/beacon-biosignals/Ray.jl/pull/193 as it contains more changes than I think is suitable for this PR

File: src/object_ref.jl [hunk 6]
```diff
@@ -63,7 +63,8 @@ function Base.deepcopy_internal(x::ObjectRef, stackdict::IdDict)
     return xcp
 end
 
-function ObjectRef(oid::ray_jll.ObjectIDAllocated; kwargs...)
+function ObjectRef(oid::Union{ray_jll.ObjectIDAllocated,ray_jll.ObjectIDDereferenced};
+                   kwargs...)
```
[the remark this answers is not in the document]
Comment (kleinschmidt) [reply src/object_ref.jl:67]: that's just 
```suggestion
function ObjectRef(oid::ray_jll.ObjectID; kwargs...)
```

right?

File: build/wrapper.cc [hunk 7]
```diff
@@ -180,31 +185,33 @@ ray::core::CoreWorker &_GetCoreWorker() {
...
-    ObjectID object_id;
-    RAY_CHECK_OK(worker.Put(*object, contained_object_ids, &object_id));
-    return object_id;
+    auto status = worker.Put(*object, contained_object_ids, object_id);
+    return status;
 }
 
 // Example of using `CoreWorker::Get`: https://github.com/ray-project/ray/blob/ray-2.5.1/src/ray/core_worker/test/core_worker_test.cc#L210-L220
-std::shared_ptr<RayObject> get(const ObjectID object_id, int64_t timeout_ms) {
+Status get(const ObjectID object_id, int64_t timeout_ms, std::vector<std::shared_ptr<RayObject>> *objects) {
```
[the remark this answers is not in the document]
Comment (kleinschmidt) [reply build/wrapper.cc:199]: (I agree with @omus suggestion here though)

**Review by kleinschmidt — COMMENTED** [review]
this is a bit more in-depth than what I had in mind, which was to throw runtime errors instead of using the `RAY_CHECK` macro.  but generally in the right direction.

if we're going to make all these JLL functions have the same kind of interface as the C++ ones (pass in pointer to return args, return `Status`), I think there are a few more places that need to be brought into alignment with that (look for places where the status is checked for `ok()` and runtime exceptiosn raised if not...)

File: build/wrapper.cc (hunk 7 above)
[the remark this answers is not in the document]
Comment (glennmoy) [reply build/wrapper.cc:198]: So..having trouble with the "re-instante the vector" part...

We give a pointer to a ` shared_ptr<RayObject>` (`result`), but the coreworker function takes a pointer to a `vector<shared_ptr<RayObject>>` (`result_vec`).

It's not as simple as wrappring `result` in a vector since then we'd have a pointer to a vector of _pointers_.
And it's also not viable to set the `result` to point to `&result_vec[0]` after the fact either since I'm pretty sure that memory is released once `get` returns.

I tried to `memcpy` the actual data in `result_vec` into the address of `result` but that wasn't working out either.

I want to completely avoid `reinterpret_cast` and friends since those are too dangerous but I'm open to any ideas?

IMO, I think passing a `vector<shared_ptr<RayObject>>` would be fine as  it's consistent with the function signature of the coreworker functions. It's also much easier to extract the `only` value in the `results` on the julia-side.

[the remark this answers is not in the document]
Comment (glennmoy) [reply build/wrapper.cc:198]: > I also tried to memcpy the actual data in result_vec into the address of result but that wasn't working out either.
Specifically I used `std::memcpy(result, &result_vec[0], sizeof(shared_ptr<RayObject>))`

[the remark this answers is not in the document]
Comment (kleinschmidt) [reply build/wrapper.cc:198]: > In any case IMO, I think passing a vector<shared_ptr<RayObject>> would be fine as it's consistent with the function signature of the coreworker functions. It's also much easier to extract the only value in the results on the julia-side.

Okay, that's fine.  Don't get too bogged down here.  I'm annoyed that we are leaking so much of the C++ stuff into the Ray.jl codebase but it seems like that ship has sailed, especially since we've lost the distinction between the jll packager and Ray.jl itself.

Just leave a comment in the julia code explaining why you have to wrap in a vector.

[the remark this answers is not in the document]
Comment (omus) [reply build/wrapper.cc:198]: > And it's also not viable to set the `result` to point to `&result_vec[0]` after the fact either since I'm pretty sure that memory is released once get returns.

As we're dealing with `shared_ptr`s here as long as you have one pointer to the memory you are using it will be retained. We should definitely be able to do this but I suspect you'll need to have a `std::shared_ptr<RayObject> *` so you can update the passed in parameter. I'll note this [`std::swap`](https://cplusplus.com/reference/memory/shared_ptr/swap-free/) function kinda does what we want but I don't think it's necessary

[the remark this answers is not in the document]
Comment (omus) [reply build/wrapper.cc:198]: This is my impression on how this would be done:
```cpp
Status get(const ObjectID object_id, int64_t timeout_ms, std::shared_ptr<RayObject> *result) {
    std::vector<std::shared_ptr<RayObject>> objects;
    auto status = worker.Get(get_obj_ids, timeout_ms, &objects);
    *result = objects[0];
    ...
}
```
The `std::shared_ptr`'s data is stored on the heap.

[the remark this answers is not in the document]
Comment (glennmoy) [reply build/wrapper.cc:198]: I will give this a shot..I had initially tried `result = &objects[0]` but I realise in hindsight I was just reassigning the _address_ of `result` and not the contents.

[the remark this answers is not in the document]
Comment (glennmoy) [reply build/wrapper.cc:198]: worked 👍

File: build/wrapper.cc [hunk 8]
```diff
@@ -180,31 +185,34 @@ ray::core::CoreWorker &_GetCoreWorker() {
...
 
     // Retrieve our data from the object store
-    std::vector<std::shared_ptr<RayObject>> objects;
     std::vector<ObjectID> get_obj_ids = {object_id};
-    auto status = worker.Get(get_obj_ids, timeout_ms, &objects);
-    if (!status.ok()) {
-        return nullptr;
+    std::vector<shared_ptr<RayObject>> result_vec;
+    auto status = worker.Get(get_obj_ids, timeout_ms, &result_vec);
+    *result = result_vec[0];
```
Comment (glennmoy) [inline build/wrapper.cc:205]: this was infuriatingly simple in the end 🤦

Comment (omus) [reply build/wrapper.cc:205]: Thanks for sticking with it ❤️

File: src/object_store.jl [hunk 9]
```diff
@@ -26,9 +28,11 @@ captured exception will be thrown on `get`.
...
 function get(obj_ref::ObjectRef)
     wait(obj_ref)
-    ray_obj = ray_jll.get(obj_ref.oid, 0)
-    isnull(ray_obj[]) && error("got null pointer after successful `wait`; this is a bug!")
-    return deserialize_from_ray_object(ray_obj, obj_ref)
+    ray_objs = CxxPtr(SharedPtr{ray_jll.RayObject}())
+    status = ray_jll.get(obj_ref.oid, 0, ray_objs)
+    Symbol(status) == :OK || error("ray_julia_jll.get returned Status::$status")
+    isnull(ray_objs) && error("got null pointer after successful `wait`; this is a bug!")
+    return deserialize_from_ray_object(ray_objs[], obj_ref)
```
Comment (omus) [inline src/object_store.jl:35]:
```suggestion
    ray_obj = CxxPtr(SharedPtr{ray_jll.RayObject}())
    status = ray_jll.get(obj_ref.oid, 0, ray_obj)
    Symbol(status) == :OK || error("ray_julia_jll.get returned Status::$status")
    isnull(ray_obj) && error("got null pointer after successful `wait`; this is a bug!")
    return deserialize_from_ray_object(ray_obj[], obj_ref)
```

File: test/ray_julia_jll/put_get.jl [hunk 10]
```diff
@@ -11,13 +11,17 @@ using .ray_julia_jll: ObjectID
...
+        @test Symbol(status) == :OK
+        @test ray_julia_jll.contains(oid[])
 
         # TODO: Currently uses size/length from `data`
         # https://github.com/beacon-biosignals/Ray.jl/issues/55
-        ray_obj = ray_julia_jll.get(oid, -1)
-        buffer = GetData(ray_obj[])
+        ray_obj = CxxPtr(SharedPtr{ray_jll.RayObject}())
+        status = ray_julia_jll.get(oid[], -1, ray_obj)
+        @test Symbol(status) == :OK
```
Comment (omus) [inline test/ray_julia_jll/put_get.jl:23]: Testing it this way ensures that a `Status` type is returned or at least comparable
```suggestion
        @test status == Status(:OK)
```
Will need to import `Status`

File: test/ray_julia_jll/put_get.jl [hunk 11]
```diff
@@ -32,11 +36,15 @@ using .ray_julia_jll: ObjectID
     @testset "roundtrip string" begin
         data = "Greetings from Julia!"
         buffer = LocalMemoryBuffer(Ptr{Nothing}(pointer(data)), sizeof(data), true)
-        oid = ray_julia_jll.put(RayObject(buffer), StdVector{ObjectID}())
-        @test ray_julia_jll.contains(oid)
+        oid = CxxPtr(ray_jll.ObjectID())
+        status = ray_julia_jll.put(RayObject(buffer), StdVector{ObjectID}(), oid)
+        @test Symbol(status) == :OK
```
Comment (omus) [inline test/ray_julia_jll/put_get.jl:41]:
```suggestion
        @test status == Status(:OK)
```

File: test/ray_julia_jll/put_get.jl [hunk 12]
```diff
@@ -32,11 +36,15 @@ using .ray_julia_jll: ObjectID
...
+        @test ray_julia_jll.contains(oid[])
 
-        ray_obj = ray_julia_jll.get(oid, -1)
-        buffer = GetData(ray_obj[])
+        ray_obj = CxxPtr(SharedPtr{ray_jll.RayObject}())
+        status = ray_julia_jll.get(oid[], -1, ray_obj)
+        @test Symbol(status) == :OK
```
Comment (omus) [inline test/ray_julia_jll/put_get.jl:46]:
```suggestion
        @test status == Status(:OK)
```

File: test/ray_julia_jll/put_get.jl [hunk 13]
```diff
@@ -11,13 +11,17 @@ using .ray_julia_jll: ObjectID
     @testset "roundtrip vector" begin
         data = UInt16[1:3;]
         buffer = LocalMemoryBuffer(Ptr{Nothing}(pointer(data)), sizeof(data), true)
-        oid = ray_julia_jll.put(RayObject(buffer), StdVector{ObjectID}())
-        @test ray_julia_jll.contains(oid)
+        oid = CxxPtr(ray_jll.ObjectID())
+        status = ray_julia_jll.put(RayObject(buffer), StdVector{ObjectID}(), oid)
+        @test Symbol(status) == :OK
```
Comment (omus) [inline test/ray_julia_jll/put_get.jl:16]:
```suggestion
        @test status == Status(:OK)
```

File: build/wrapper.cc [hunk 14]
```diff
@@ -110,13 +110,18 @@ void initialize_worker(
...
-          (*returns)[0].second = return_vec[0];
-          return Status::OK();
+          if (return_vec.size() == 1) {
+            (*returns)[0].second = return_vec[0];
+            return Status::OK();
+          }
+          else {
+            auto msg = "Task returned " + std::to_string(return_vec.size()) + " values. Expected 1.";
+            return Status::NotImplemented(msg);
+          };
```
Comment (omus) [inline build/wrapper.cc:122]: Indentation
```suggestion
          if (return_vec.size() == 1) {
              (*returns)[0].second = return_vec[0];
              return Status::OK();
          }
          else {
              auto msg = "Task returned " + std::to_string(return_vec.size()) + " values. Expected 1.";
              return Status::NotImplemented(msg);
          };
```

**Review by omus — APPROVED** [review]
A couple minor things

File: test/ray_julia_jll/put_get.jl (hunk 10 above)
Comment (glennmoy) [reply test/ray_julia_jll/put_get.jl:23]: ah yeah I was trying to figure out the inverse of that and was using `StatusCode` 👍

File: build/wrapper.cc (hunk 14 above)
Comment (glennmoy) [reply build/wrapper.cc:122]: the whole block is indented wrong

File: test/ray_julia_jll/put_get.jl (hunk 10 above)
Comment (glennmoy) [reply test/ray_julia_jll/put_get.jl:23]: I think the difference is that the Enum is a `StatusCode` while the return of the function is a `Status`

Comment (glennmoy) [reply test/ray_julia_jll/put_get.jl:23]: alt:
```julia
julia> ray_julia_jll.ok(status)
true

julia> ray_julia_jll.code(status) == ray_julia_jll.StatusCode(:OK)
true
```
